[package]
name = "vunerable-transaction-service"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.7"
tokio = { version="1", features=["full"] }
scylla = "0.12"
serde = { version="1", features=["derive"] }
